HumanBrainBox/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HumanBrainBox.Business;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HumanBrainBox.Data;
using HumanBrainBox.Data.Models.Contacts;
using HumanBrainBox.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace HumanBrainBox.Controllers
{
    [Authorize]
    public class ContactsController : HumanBrainBoxBaseController
    {


        public ContactsController(ApplicationDbContext dbContext, 
                                  UserManager<ApplicationUser> userManager, 
                                  IHttpContextAccessor httpContextAccessor) : base (httpContextAccessor, dbContext, userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            

        }
        // GET: Contacts
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            return View(await _dbContext.Contact.Where(x => x.OwnerID == userId).ToListAsync());
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _dbContext.Contact
                .SingleOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {   
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Address,City,State,Zip,Email")] Contact contact)
        {
            if (!ModelState.IsValid)
            {
                return View(contact);
            }

            contact.OwnerID = _userManager.GetUserId(User);

            _dbContext.Add(contact);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            
            
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _dbContext.Contact.SingleOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContactId,Name,Address,City,State,Zip,Email")] Contact contact)
        {
            if (id != contact.ContactId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _dbContext.Update(contact);
                    await _dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactExists(contact.ContactId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _dbContext.Contact
                .SingleOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _dbContext.Contact.SingleOrDefaultAsync(m => m.ContactId == id);
            _dbContext.Contact.Remove(contact);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(int id)
        {
            return _dbContext.Contact.Any(e => e.ContactId == id);
        }
    }
}

HumanBrainBox/Controllers/DashboardController.cs
using System;
using HumanBrainBox.Business;
using HumanBrainBox.Data;
using HumanBrainBox.Models;
using HumanBrainBox.Models.DashboardViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace HumanBrainBox.Controllers
{
	[Authorize]
    //[Route("[controller]/[action]")]
    public class DashboardController : HumanBrainBoxBaseController
    {

	    private readonly SignInManager<ApplicationUser> _loginManager;
	    //private readonly RoleManager<ApplicationRole> _roleManager;


	    public DashboardController(ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager,
		    SignInManager<ApplicationUser> loginManager, IHttpContextAccessor httpContextAccessor) :
		    base(httpContextAccessor, dbContext, userManager)
	    {
		    _dbContext = dbContext;
		    _userManager = userManager;
		    _loginManager = loginManager;

	    }

	    

		[TempData]
        public string StatusMessage { get; set; }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var model = new DashboardHomeViewModel
            {
                ApplicationUser = user
            };

            return View(model);
        }



        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }



        #endregion
    }
}

HumanBrainBox/Views/Shared/_Footer.cshtml
<footer class="footer">
    <span class="pull-right">
        Copyright
    </span>
    HumanBrainBox @DateTime.Now.Year
</footer>

HumanBrainBox/Views/Shared/_Header.cshtml
<div class="color-line">
</div>
<div id="logo" class="light-version">
    <a class="h4" href="@Url.Action("Index", "Dashboard")">HumanBrainBox</a>
</div>

<nav role="navigation">
    <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
    <div class="small-logo">
        <span class="text-primary">Dashboard Home</span>
    </div>
    @*<form role="search" class="navbar-form-custom" method="post" action="#">
        <div class="form-group">
            <input type="text" placeholder="Search something special" class="form-control" name="search">
        </div>
    </form>*@
    <div class="mobile-menu">
        <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
            <i class="fa fa-chevron-down"></i>
        </button>
        <div class="collapse mobile-navbar" id="mobile-collapse">
            <ul class="nav navbar-nav">
                @await Html.PartialAsync("_LoginPartial")
                <li>
                    <a class="" href="">Profile</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="white navbar-right">
        <ul class="nav navbar-nav no-borders">
            <li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe-7s-speaker"></i>
                </a>
                <ul class="dropdown-menu hdropdown notification animated flipInX">
                    <li>
                        <a>
                            <span class="label label-success">NEW</span> It is a long established.
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="label label-warning">WAR</span> There are many variations.
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="label label-danger">ERR</span> Contrary to popular belief.
                        </a>
                    </li>
                    <li class="summary"><a href="#">See all notifications</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe pe-7s-users text-success"></i>
                </a>
                <div class="dropdown-menu hdropdown bigmenu animated flipInX">
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <a href="">
                                        <i class="pe pe-7s-portfolio text-info"></i>
                                        <h5>Projects</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="">
                                        <i class="pe pe-7s-mail text-warning"></i>
                                        <h5>Email</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Index", "Contacts")">
                                        <i class="pe pe-7s-users text-success"></i>
                                        <h5>Contacts</h5>
                                    </a>
                                </td>
                            </tr>   
                        </tbody>
                    </table>
                </div>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle label-menu-corner" href="#" data-toggle="dropdown">
                    <i class="pe-7s-mail"></i>
                    <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu hdropdown animated flipInX">
                    <div class="title">
                        You have 4 new messages
                    </div>
                    <li>
                        <a>
                            It is a long established.
                        </a>
                    </li>
                    <li>
                        <a>
                            There are many variations.
                        </a>
                    </li>
                    <li>
                        <a>
                            Lorem Ipsum is simply dummy.
                        </a>
                    </li>
                    <li>
                        <a>
                            Contrary to popular belief.
                        </a>
                    </li>
                    <li class="summary"><a href="#">See All Messages</a></li>
                </ul>
            </li>
            <li>
                <a href="#" id="sidebar" class="right-sidebar-toggle">
                    <i class="pe-7s-upload pe-7s-news-paper"></i>
                </a>
            </li>
            <li class="dropdown">
                <a href="@Url.Action("Logout", "Account")">
                    <i class="pe-7s-upload pe-rotate-90"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

HumanBrainBox/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Human Brain Box</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <environment names="Development">
        <link rel="stylesheet" href="~/lib_local/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/lib/animate.css/animate.css" />
        <link rel="stylesheet" href="~/Icons/pe-icon-7-stroke/css/pe-icon-7-stroke.css" />
        <link rel="stylesheet" href="~/lib_local/metisMenu/dist/metisMenu.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib_local/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
        <link rel="stylesheet" href="~/Icons/pe-icon-7-stroke/css/pe-icon-7-stroke.css" />
        <link rel="stylesheet" href="~/lib_local/metisMenu/dist/metisMenu.min.css" />
        <link rel="stylesheet" href="~/css/style.min.css" asp-append-version="true" />
    </environment>
</head>
<body class="light-skin fixed-navbar sidebar-scroll">
    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header -->
    <div id="header">
        @Html.Partial("_Header")
    </div>

    <!-- Navigation -->
    <aside id="menu">
        @Html.Partial("_Navigation")
    </aside>

    <!-- Main view  -->
    <div id="wrapper">
        @RenderBody()

        <!-- Right Sidebar -->
        @Html.Partial("_Right_Sidebar")

        <!-- Footer-->
        @Html.Partial("_Footer")
    </div>

    <environment names="Development">
        <script src="~/lib_local/jquery/dist/jquery.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.js"></script>
        <script src="~/lib_local/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/iCheck/icheck.js"></script>
        <script src="~/lib_local/metisMenu/dist/metisMenu.js"></script>
        <script src="~/lib_local/sparkline/index.js"></script>
        <script src="~/js/homer.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib_local/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="~/lib_local/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/iCheck/icheck.min.js"></script>
        <script src="~/lib_local/metisMenu/dist/metisMenu.min.js"></script>
        <script src="~/lib_local/sparkline/index.js"></script>
        <script src="~/js/homer.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

HumanBrainBox/Views/Shared/_Layout_Blank.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HBB</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
            {@RenderSection("Styles", required: false)}

    <environment names="Development">
        <link rel="stylesheet" href="~/lib_local/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/lib/animate.css/animate.css" />
        <link rel="stylesheet" href="~/Icons/pe-icon-7-stroke/css/pe-icon-7-stroke.css" />
        <link rel="stylesheet" href="~/lib_local/metisMenu/dist/metisMenu.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib_local/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
        <link rel="stylesheet" href="~/Icons/pe-icon-7-stroke/css/pe-icon-7-stroke.css" />
        <link rel="stylesheet" href="~/lib_local/metisMenu/dist/metisMenu.min.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>


    @*@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)*@
</head>
<body class="blank">

    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="color-line"></div>

    <div class="back-link">
        <a href="@Url.Action("Index", "Home")" class="btn btn-primary">Back to Homepage</a>
    </div>

    <!-- Main view  -->
    @RenderBody()

    <environment names="Development">
        <script src="~/lib_local/jquery/dist/jquery.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.js"></script>
        <script src="~/lib_local/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/iCheck/icheck.js"></script>
        <script src="~/lib_local/metisMenu/dist/metisMenu.js"></script>
        <script src="~/lib_local/sparkline/index.js"></script>
        <script src="~/js/homer.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib_local/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="~/lib_local/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/iCheck/icheck.min.js"></script>
        <script src="~/lib_local/metisMenu/dist/metisMenu.min.js"></script>
        <script src="~/lib_local/sparkline/index.js"></script>
        <script src="~/js/homer.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

HumanBrainBox/Views/Shared/_Layout_Landing.cshtml
@using Microsoft.ApplicationInsights.Extensibility
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Homer_MVC</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <environment names="Development">
        <link rel="stylesheet" href="~/lib_local/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/lib/animate.css/animate.css" />
        <link rel="stylesheet" href="~/Icons/pe-icon-7-stroke/css/pe-icon-7-stroke.css" />
        <link rel="stylesheet" href="~/lib_local/metisMenu/dist/metisMenu.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib_local/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
        <link rel="stylesheet" href="~/Icons/pe-icon-7-stroke/css/pe-icon-7-stroke.css" />
        <link rel="stylesheet" href="~/lib_local/metisMenu/dist/metisMenu.min.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>


    @*@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)*@
</head>
<body class="landing-page">

    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Main view  -->
    @RenderBody()

    <environment names="Development">
        <script src="~/lib_local/jquery/dist/jquery.js"></script>
        <script src="~/lib_local/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/iCheck/icheck.js"></script>
        <script src="~/lib_local/metisMenu/dist/metisMenu.js"></script>
        <script src="~/lib_local/sparkline/index.js"></script>
        <script src="~/js/homer.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib_local/jquery/dist/jquery.min.js"></script>
        <script src="~/lib_local/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/iCheck/icheck.min.js"></script>
        <script src="~/lib_local/metisMenu/dist/metisMenu.min.js"></script>
        <script src="~/lib_local/sparkline/index.js"></script>
        <script src="~/js/homer.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

HumanBrainBox/Views/Shared/_PageHeader.cshtml
@using Microsoft.AspNetCore.Html

<div class="row">
    <div class="col-lg-12">
        <div class="normalheader small-header">
            <div class="hpanel">
                <div class="panel-body">
                    <a class="small-header-action" href="">
                        <div class="clip-header">
                            <i class="fa fa-arrow-down"></i>
                        </div>
                    </a>

                    <div id="hbreadcrumb" class="pull-right">

                        <ol class="hbreadcrumb breadcrumb">
                            @if (ViewData["BreadCrumbs"] != null)
                            {
                                foreach (var item in (List<IHtmlContent>) ViewData["BreadCrumbs"])
                                {
                                    <li>
                                        @item
                                    </li>
                                }
                            }
                            <li class="active">
                                <span>@ViewData["Title"]</span>
                            </li>
                        </ol>
                    </div>
                    <h2 class="font-light m-b-xs">
                        @ViewData["Title"]
                    </h2>
                    <small>@ViewData["SubTitle"]</small>
                </div>
            </div>
        </div>
    </div>

</div>

HumanBrainBox/Views/Shared/_Right_Sidebar.cshtml
<div id="right-sidebar" class="animated fadeInRight">

    <div class="p-m">
        <button id="sidebar-close" class="right-sidebar-toggle sidebar-button btn btn-default m-b-md">
            <i class="pe pe-7s-close"></i>
        </button>
        <div>
            <span class="font-bold no-margins"> Analytics </span>
            <br>
            <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
        </div>
        <div class="row m-t-sm m-b-sm">
            <div class="col-lg-6">
                <h3 class="no-margins font-extra-bold text-success">300,102</h3>

                <div class="font-bold">98% <i class="fa fa-level-up text-success"></i></div>
            </div>
            <div class="col-lg-6">
                <h3 class="no-margins font-extra-bold text-success">280,200</h3>

                <div class="font-bold">98% <i class="fa fa-level-up text-success"></i></div>
            </div>
        </div>
        <div class="progress m-t-xs full progress-small">
            <div style="width: 25%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="25" role="progressbar"
                 class=" progress-bar progress-bar-success">
                <span class="sr-only">35% Complete (success)</span>
            </div>
        </div>
    </div>
    <div class="p-m bg-light border-bottom border-top">
        <span class="font-bold no-margins"> Social talks </span>
        <br>
        <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
        <div class="m-t-md">
            <div class="social-talk">
                <div class="media social-profile clearfix">
                    <a class="pull-left">
                        <img src="~/Images/a1.jpg" alt="profile-picture">
                    </a>

                    <div class="media-body">
                        <span class="font-bold">John Novak</span>
                        <small class="text-muted">21.03.2015</small>
                        <div class="social-content small">
                            Injected humour, or randomised words which don't look even slightly believable.
                        </div>
                    </div>
                </div>
            </div>
            <div class="social-talk">
                <div class="media social-profile clearfix">
                    <a class="pull-left">
                        <img src="~/Images/a3.jpg" alt="profile-picture">
                    </a>

                    <div class="media-body">
                        <span class="font-bold">Mark Smith</span>
                        <small class="text-muted">14.04.2015</small>
                        <div class="social-content">
                            Many desktop publishing packages and web page editors.
                        </div>
                    </div>
                </div>
            </div>
            <div class="social-talk">
                <div class="media social-profile clearfix">
                    <a class="pull-left">
                        <img src="~/Images/a4.jpg" alt="profile-picture">
                    </a>

                    <div class="media-body">
                        <span class="font-bold">Marica Morgan</span>
                        <small class="text-muted">21.03.2015</small>

                        <div class="social-content">
                            There are many variations of passages of Lorem Ipsum available, but the majority have
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="p-m">
        <span class="font-bold no-margins"> Sales in last week </span>
        <div class="m-t-xs">
            <div class="row">
                <div class="col-xs-6">
                    <small>Today</small>
                    <h4 class="m-t-xs">$170,20 <i class="fa fa-level-up text-success"></i></h4>
                </div>
                <div class="col-xs-6">
                    <small>Last week</small>
                    <h4 class="m-t-xs">$580,90 <i class="fa fa-level-up text-success"></i></h4>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <small>Today</small>
                    <h4 class="m-t-xs">$620,20 <i class="fa fa-level-up text-success"></i></h4>
                </div>
                <div class="col-xs-6">
                    <small>Last week</small>
                    <h4 class="m-t-xs">$140,70 <i class="fa fa-level-up text-success"></i></h4>
                </div>
            </div>
        </div>
        <small>
            Lorem Ipsum is simply dummy text of the printing simply all dummy text.
            Many desktop publishing packages and web page editors.
        </small>
    </div>

</div>